### ISSUE TITLE
Anonymous User Posting Back-End

### ISSUE THREAD

**Issue by J0nathanLai** [CMU-313/nodebb-f24-team-wooshiland#13]
Estimated effort for each task: 20 hours
Dependencies among tasks: Front-end of Anonymous User Posting
Initial assignments for team members: Anna & Jonathan
Milestones to indicate which sprint the issue should be completed in (Sprint 1, Sprint 2, Stretch): Sprint 1
Acceptance criteria that describes how you know this task is done - think about how you will test this feature: Write tests so code passes all the tests.

**Comment by sophiefeng18** [comment]
broke down into more specific isssues
