### ISSUE TITLE
Add a Tag Display to Anonymous Posts [front-end]

### ISSUE THREAD

**Issue by J0nathanLai** [CMU-313/nodebb-f24-team-wooshiland#24]
Indicate the post is anonymous to instructors.

**Estimated effort for each task:** Medium
**Dependencies among tasks:** permissions and anonymous post button
**Milestones to indicate which sprint the issue should be completed in (Sprint 1, Sprint 2, Stretch):** Sprint 2
**Acceptance criteria that describes how you know this task is done:** Test on whether an anonymous post tag shows up on the instructors' screen after a student posts an anonymous post.

**Comment by kmehta5** [comment]
Completed adding a tag on posts, need to resolve dependency of adding back end logic. 
Changes committed to "anonymous-tag" branch of front-end reop (no changes on main repo).
